### ISSUE TITLE
Estudar Conceitos e Tecnologias 

### ISSUE THREAD

**Issue by LeticiaMonteiroo** [unb-mds/2024-2-Squad05#1]
## Descrição da Tarefa

Para iniciar um bom projeto, é essencial estudar conceitos e tecnologias fundamentais. No entanto, nem todos do grupo terão tempo ou habilidade para se aprofundar em todos os assuntos ao mesmo momento. Com base nisso, o Squad 5 decidiu adotar a "Metodologia da Lebre", onde cada integrante se especializa em um tema específico e depois compartilha seu conhecimento com os demais.

## Tecnologias e Conceitos 
***Git*** – commit/pull/push/status/branch/Padrão de commit - Laryssa
***Github*** – Issues/Milestone/Labels/Projects - Letícia
***GitPage*** – Markdown / Html&CSS - Arthur
***Configurar Ambiente*** – Docker - Luiz
***CI/CD*** – Integração Contínua e Entrega Contínua - Caio
***Metodologias Ágeis e Roadmap*** – início projeto (Scrum e XP) característica de projetos opensource - Gabriel

## Critérios de Aceitação

- [x] Estudar os tópicos propostos
- [x] Criar uma apresentação objetiva
- [x] Compartilhar boas fontes de estudo

## Requisitos
A quais requisitos do projeto esta questão se refere?
- Não se aplica.

## Informações Adicionais

-

**Comment by felixlaryssa** [comment]
**Documentos dos meus estudos da sprint 0:**

1- Padronização da mensagem de commit que será adota pela equipe:
https://docs.google.com/document/d/1MELhEDFKfd5hHLR40s0uJAlfozTmgvRsDrXE2UpvHjs/edit?usp=sharing

2-Padronização da nomenclatura da branch:
https://docs.google.com/document/d/1f3j9ViylR-GrR9C8QozVlmsrdQiaxzp5bsZgg2j8OSQ/edit?usp=sharing

3-Comandos de git:
https://training.github.com/downloads/pt_BR/github-git-cheat-sheet.pdf

**Comment by CaioPacheco** [comment]
Não esqueçam de colocar as fontes de estudo aqui como comentário. 
@arthurfernandesj @GabrielSPinto @luizh-gsoares

**Comment by arthurfernandesj** [comment]
Documento do meu estudo sobre a Sprint 0:

1. Sobre Markdown
https://docs.google.com/document/d/1AsdR8_DQJ9oBc8sMKoimeEg0M952CoUy0QIWs5oDhUM/edit?usp=sharing
link caso precise de ajuda, pois é o mesmo documento: https://docs.github.com/pt/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

2. Sobre o GitPage está em produção para estar no ar, ainda estou pesquisando sobre. Mas para fazer o deploy do gitpage tem esse link que ajudará a equipe sobre. 
https://www.alura.com.br/artigos/como-colocar-projeto-no-ar-com-github-pages?srsltid=AfmBOorUoe6kj67zin6tWq1w9nklFMPZd0FmYwtamafAV4Q97t51vG4b

**Comment by luizh-gsoares** [comment]
Essas aqui são as melhores referências por onde estudei Docker e que eu recomendo dar uma olhada:

- [Docker Learning Roadmap](https://roadmap.sh/docker)
- [Docker Cheat Sheet](https://docs.docker.com/get-started/docker_cheatsheet.pdf)
- [Livro Descomplicando Docker](https://livro.descomplicandodocker.com.br/)
- [Vídeo: Introdução ao Docker para iniciantes | Docker Tutorial](https://youtu.be/01MR38eDXz8)
- [Documentação Oficial do Docker](https://docs.docker.com/)
- [Play with Docker Labs](https://labs.play-with-docker.com/)

**Comment by GabrielSPinto** [comment]
Documentos dos meus estudos da sprint 0:

[SCRUM](http://ned.unifenas.br/cursosgratuitos/201302/scrum/funcionamento.html)

[Roadmap](https://miro.com/pt/agile/o-que-e-roadmap/)

[O MAPA DE HISTÓRIAS (STORY MAPPING) E ROADMAP DE PRODUTO](https://medium.com/management-and-it-innovation/o-mapa-de-hist%C3%B3rias-story-mapping-e-roadmap-de-produto-f6ea7dd8dac5)

[Exemplo de documentação visual do projeto LicitaBSB-24.1](https://miro.com/app/board/uXjVKcAWUlc=/)

**Comment by LeticiaMonteiroo** [comment]
Link da Documentação do Github sobre:

Issues: https://docs.github.com/pt/issues/tracking-your-work-with-issues/about-issues
Milestone: https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work
Labels: https://docs.github.com/pt/issues/using-labels-and-milestones-to-track-work/managing-labels
Projects: https://docs.github.com/pt/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects
