### ISSUE TITLE
Organização da Documentação

### ISSUE THREAD

**Issue by felixlaryssa** [unb-mds/2024-2-Squad05#10]
## Descrição da Tarefa

Criação do Miro com documentação visual do projeto

## Critérios de Aceitação

- [ ] Quadro no miro com os itens dos requisitos

## Requisitos

- [x] Storymap
- [x] Sprints com detalhamento de issues
- [x] Ícones com responsáveis estatus da tarefa
- [x] Detalhamento das Releases
- [x] Retrospectivas
- [x] Chuva de Ideias
- [x] Espaço para arquitetura
- [x] Rotação do Scrum Master
- [x] Resumo das Sprints

## Informações Adicionais

O que mais vier

**Comment by GabrielSPinto** [comment]
Link do borad: [AQUI](https://miro.com/app/board/uXjVLKNGzd8=/?share_link_id=694261516850)

**Comment by GabrielSPinto** [comment]
Decidimos colocar a arquitetura num miro próprio
