### ISSUE TITLE
Criação de GitPage para o Projeto

### ISSUE THREAD

**Issue by felixlaryssa** [unb-mds/2024-2-Squad05#12]
## Descrição da Tarefa

Criação e configuração da Git Page do projeto

## Critérios de Aceitação

- [x] Configurar **MK docs**
- [x] Criar workflow usando **GitHub Actions**
- [x] Executar workflow
## Requisitos

_Não se aplica._

## Informações Adicionais

Outra issue #3 duplicada sobre esse assunto foi fechada.

**Comment by luizh-gsoares** [comment]
Em atualização a issue, realizei estudos agora pela noite sobre o funcionamento do GitHub Pages, GitHub Actions e da biblioteca mkdocs do python. Com esses estudos, consegui realizar o deploy da seguinte página: 

https://luizh-gsoares.github.io/TestDocumentationGithubPages.

**Comment by CaioPacheco** [comment]
A Git Page está funcionando corretamente

**Comment by luizh-gsoares** [comment]
Com a ajuda do @GabrielSPinto , realizamos as alterações na estrutura do Github Pages e está funcionando corretamente no endereço unb-mds.github.io/2024-2-Squad05/](https://unb-mds.github.io/2024-2-Squad05/).
