### ISSUE TITLE
Arquitetura de Código

### ISSUE THREAD

**Issue by felixlaryssa** [unb-mds/2024-2-Squad05#14]
## Descrição da Tarefa

Pesquisar e estudar conceitos de Arquitetura de Código, compreendendo como estruturar um projeto de software de forma eficiente, escalável e sustentável. A atividade envolve a análise de padrões arquiteturais, boas práticas de organização de código e técnicas que favoreçam a manutenibilidade e colaboração em equipe. Deve-se explorar tanto arquiteturas tradicionais quanto modernas, como MVC, arquitetura limpa e orientada a microsserviços.

## Critérios de Aceitação

- [x] Conhecer os Conceitos Fundamentais
- [x] Padrões Arquiteturais
- [x] Princípios e Boas Práticas
- [x] Documento ou imagem com resumo 

## Requisitos
A quais requisitos do projeto esta questão se refere?
- Não se aplica

**Comment by LeticiaMonteiroo** [comment]
Design de Software e Arquitetura de Software tem coisas parecidas mas não são a mesma coisa

- Arq. Foca em como os componentes vão interagir entre si, como as divisões vão ser feitas, é como a ordem dos capítulos de um livro, está separando mas interagindo entre si
- Desing foca na implementação dos componentes, tendo atenção nos detalhes

Model View Controller - MVC 

É o mais conhecido entre os padrões, muito bom porém pode apresentar problemas se a aplicação aumenta muito 

- Model cuida da parte dos dados da aplicação
- View é  a parte que exibe essas dados para cliente e permite as interações
- Controller intermédia os dois anteriores, faz o controle das informações que transitam entre eles

**Comment by LeticiaMonteiroo** [comment]
![image](https://github.com/user-attachments/assets/1301f633-d5a2-42ba-abc2-9217ddb8742b)

**Comment by LeticiaMonteiroo** [comment]
![image](https://github.com/user-attachments/assets/aac88af1-a481-4a89-83c0-178b0fc2568e)
