### ISSUE TITLE
Definir Histórias de usuários, épicos e features

### ISSUE THREAD

**Issue by felixlaryssa** [unb-mds/2024-2-Squad05#16]
## Descrição da Tarefa

Documentar e estruturar as histórias de usuários, épicos e features do projeto para organizar as entregas e alinhar os objetivos do produto às necessidades dos usuários. Essa tarefa envolve mapear os grandes temas (épicos), detalhar as funcionalidades associadas (features) e criar histórias de usuários que descrevam como cada funcionalidade atende aos objetivos do usuário.

## Critérios de Aceitação

- [x] Identificar os principais épicos do projeto (grandes temas que agrupam funcionalidades).
- [x] Listar as features relacionadas a cada épico, com foco em funcionalidades específicas do produto.
- [x] Criar histórias de usuários que detalhem o objetivo de cada funcionalidade, utilizando o formato padrão

## Requisitos
A quais requisitos do projeto esta questão se refere?
- Não se aplica

## Informações Adicionais

Adicione qualquer informação adicional que possa ser útil.

**Comment by LeticiaMonteiroo** [comment]
![image](https://github.com/user-attachments/assets/e3a8d787-3e01-4324-8961-3ae5d95cd727)
