### ISSUE TITLE
Criar Readme - Visão Geral do Projeto 

### ISSUE THREAD

**Issue by LeticiaMonteiroo** [unb-mds/2024-2-Squad05#2]
## Descrição da Tarefa

No início de um projeto, é essencial criar o README, que será parte da descrição e documentação do projeto. O README deve contextualizar o desenvolvimento, descrever o objetivo do projeto, e oferecer uma visão geral de suas funcionalidades. Além disso, é recomendável incluir instruções para instalação, configuração, e uso básico, bem como destacar as tecnologias utilizadas e possíveis pré-requisitos. 

## Critérios de Aceitação

- [x] Ser claro e objetivo 
- [x] Contextualizar o objetivo e a funções do projeto

## Requisitos
A quais requisitos do projeto esta questão se refere?
- Não se aplica

**Comment by arthurfernandesj** [comment]
Adicionei alguns elementos e, futuramente, pretendo aprimorá-los após a definição do tema. Com isso, conseguirei organizar tudo de forma mais estruturada, de acordo com os critérios de aceitação acima.

**Comment by CaioPacheco** [comment]
Revisei o arquivo, está com todas as informações que temos até agora.
