### ISSUE TITLE
Criação do Protótipo de Alta Fidelidade

### ISSUE THREAD

**Issue by luizh-gsoares** [unb-mds/2024-2-Squad05#20]
## Descrição da Tarefa

Criar protótipos interativos das principais telas e fluxos da aplicação utilizando o Figma. O objetivo é fornecer uma representação visual e funcional da interface do usuário, facilitando feedback antecipado e permitindo ajustes antes do desenvolvimento. A prototipação deve incluir os elementos de design, navegação entre telas e interações básicas, ajudando a alinhar expectativas sobre a experiência do usuário.

## Critérios de Aceitação

- [x] Está de acordo com os Requisitos 
- [x] Layout e Estilo Consistentes
- [x] Representação Completa das principais páginas
- [x]  Feedback dos outros integrantes 

## Requisitos
A quais requisitos do projeto esta questão se refere?
- Não se aplica

**Comment by LeticiaMonteiroo** [comment]
![image](https://github.com/user-attachments/assets/1450a288-4937-4a2f-ab12-af1d46f40968)
