### ISSUE TITLE
Atualização do conteúdo da GitHub Pages

### ISSUE THREAD

**Issue by luizh-gsoares** [unb-mds/2024-2-Squad05#21]
## Descrição da Tarefa

Atualizar o conteúdo da GitHub Pages do projeto para refletir as últimas mudanças feitas no repositório principal. Garantir que a documentação, informações do projeto, e outros conteúdos relevantes estejam atualizados e acessíveis para os usuários.

## Critérios de Aceitação

- [ ]O conteúdo da GitHub Pages reflete as últimas alterações do repositório principal.
- [ ]Todas as páginas estão funcionando corretamente, sem links quebrados.
- [ ]A formatação e o design seguem o padrão visual previamente definido no projeto.
- [ ]Os usuários conseguem acessar a página principal e navegar facilmente pelos conteúdos.

## Requisitos
- []Esta tarefa está vinculada aos requisitos de atualização contínua da documentação e comunicação clara com os usuários do projeto.

## Informações Adicionais

Não cabe

**Comment by GabrielSPinto** [comment]
Estruturação da gitpage seguindo o modelo:

Home

Configuração e Contribuição
- Configuração de ambiente
- Como contribuir

Arquitetura

Jornada do Produto
- Documentação Visual
- requisitos
- Product Backlog
- Sprints
- Releases Notes

Protótipo

Registros
- Organização da equipe
- Reuniões
- Estudos

**Comment by GabrielSPinto** [comment]
Seguem atualizações na gitpage: [LINK](https://unb-mds.github.io/2024-2-Squad05/)
