### ISSUE TITLE
Funcionamento do Streamlit

### ISSUE THREAD

**Issue by luizh-gsoares** [unb-mds/2024-2-Squad05#23]
## Descrição da Tarefa

Investigar e compreender como o framework Streamlit funciona para criar aplicações web interativas e baseadas em dados. 

## Critérios de Aceitação

- [x]  Explorar a documentação oficial
- [x] Ver tutoriais e exemplos práticos
- [x] Conhecimento sobre como instalar e configurar o Streamlit em um ambiente local.

## Requisitos
A quais requisitos do projeto esta questão se refere?
- Não se aplica 

## Informações Adicionais

Adicione qualquer informação adicional que possa ser útil.

**Comment by arthurfernandesj** [comment]
Todo o desenvolvimento do arquivo foi realizado por mim, seguindo cuidadosamente os critérios de aceitação estabelecidos. Em breve, anexarei o documento formalizado, incluindo todos os passos detalhados sobre o processo realizado. Durante a reunião, apresentarei uma explicação completa e clara sobre cada etapa, com ênfase especial na parte referente ao deployment.

**Comment by luizh-gsoares** [comment]
Avaliado com todos os integrantes do grupo que será utilizado o Streamlit.
