### ISSUE TITLE
Deploy da documentação

### ISSUE THREAD

**Issue by CaioPacheco** [unb-mds/2024-2-Squad05#3]
## Descrição da Tarefa

Configurar e fazer o deploy da documentação usando **MKdocs**, **GitHub Actions** e **GitHub Pages.**

## Critérios de Aceitação

- [x] Estudar tecnologias
- [x] Configurar Ambiente
- [ ] Deploy inicial

## Requisitos
A quais requisitos do projeto esta questão se refere?
- Documentação Geral

## Informações Adicionais
- [Guia MKdocs](https://www.mkdocs.org/getting-started/)

- [Deploy usando o Pages](https://www.mkdocs.org/user-guide/deploying-your-docs/)

**Comment by CaioPacheco** [comment]
A configuração do mkdocs está feita, agora só falta aprender a fazer o deploy usando **GitHub Actions**.

**Comment by arthurfernandesj** [comment]
Até sexta feira o Github Actions estará implementada.

**Comment by CaioPacheco** [comment]
Outra issue foi criada referente ao git pages. #12
