### ISSUE TITLE
Realizar prototipação de baixa fidelidade no Figma 

### ISSUE THREAD

**Issue by LeticiaMonteiroo** [unb-mds/2024-2-Squad05#6]
## Descrição da Tarefa

Criar protótipos interativos das principais telas e fluxos da aplicação utilizando o Figma. O objetivo é fornecer uma representação visual e funcional da interface do usuário, facilitando feedback antecipado e permitindo ajustes antes do desenvolvimento. A prototipação deve incluir os elementos de design, navegação entre telas e interações básicas, ajudando a alinhar expectativas sobre a experiência do usuário.

## Critérios de Aceitação

- [x] Está de acordo com os Requisitos 
- [x] Layout e Estilo Consistentes
- [x] Representação Completa das principais páginas
- [x]  Feedback dos outros integrantes 

## Requisitos
A quais requisitos do projeto esta questão se refere?
- Não se aplica

**Comment by arthurfernandesj** [comment]
Minha parte do protótipo já foi finalizada. Qualquer mudança necessária só me informar. 
Falta apenas a parte dos tópicos recorrentes.

**Comment by LeticiaMonteiroo** [comment]
Protótipo da home finalizado
