### ISSUE TITLE
Raspagem e Análise de Dados 

### ISSUE THREAD

**Issue by LeticiaMonteiroo** [unb-mds/2024-2-Squad05#9]
## Descrição da Tarefa

Realizar um estudo aprofundado sobre técnicas de raspagem (web scraping) e análise de dados, com foco nas ferramentas, métodos e boas práticas.

## Critérios de Aceitação

- [x] Compreensão das Técnicas de Raspagem
- [x] Uso de Ferramentas de Análise de Dados
- [x] Visualização e Interpretação de Dados

## Requisitos
A quais requisitos do projeto esta questão se refere?
- Não se aplica

**Comment by arthurfernandesj** [comment]
O arquivo abaixo é sobre a raspagem já feita do brasil participativo, onde foi extraido todos os comentários, com nome, etc. Já da para visualizar os dados coletados.
[brasilparticipativo-proposal_comments.zip](https://github.com/user-attachments/files/17782511/brasilparticipativo-proposal_comments.zip)

O arquivo logo abaixo é de todo o site, mas acredito que não usaremos tudo além dos comentários.
[brasilparticipativo.presidencia.gov.br-open-data.zip](https://github.com/user-attachments/files/17782518/brasilparticipativo.presidencia.gov.br-open-data.zip)

O uso de ferramentas onde pode ajudar para extrair arquivos do site são:

1. https://docs.scrapy.org/en/latest/topics/api.html
2. https://beautiful-soup-4.readthedocs.io/en/latest/#making-the-soup

esse segundo eu achei ele interessante, e da para se aprofundar ainda mais no assunto.

**Comment by arthurfernandesj** [comment]
O arquivo em pdf é so uma mini explicação das bibliotecas de python que podemos usar no trabalho
[Linguagem Python.pdf](https://github.com/user-attachments/files/17787113/Linguagem.Python.pdf)
